name: ci
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
env:
  FORCE_COLOR: 3
concurrency:
  group: ${{ github.ref_name }}
  # Only cancel concurrent builds when we are not on the default branch. This
  # way, if a commit breaks the default branch, we can more easily determine
  # which commit caused the failure.
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}
jobs:
  ci:
    name: CI
    # Skip building tags; an identical job for the commit to which the tag
    # points will be triggered anyway.
    if: github.ref_type != 'tag'
    runs-on: ubuntu-latest
    steps:

      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Capture Environment Variables
        run: |
          echo "GIT_VERSION=$(git describe --tags --always)" >> $GITHUB_ENV
          echo "GIT_REPO=${{ github.repository }}" >> $GITHUB_ENV
          echo "GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          echo "RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Install Dependencies
        run: npm clean-install

      - name: Build Project
        run: npx nr build

      - name: Smoke Tests
        run: npx nr test.smoke.all

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx nr release

      - name: Post-Release / Send Success Notification
        if: ${{ success() }}
        run: |
          curl -s \
          --form-string "user=${{ secrets.PUSHOVER_USER }}" \
          --form-string "token=${{ secrets.PUSHOVER_TOKEN }}" \
          --form-string "message=🚀 Successfully released $GIT_VERSION of $GIT_REPO from branch $GIT_BRANCH." \
          --from-string "url=$RUN_URL" \
          --from-string "url_title=View Workflow Run" \
          https://api.pushover.net/1/messages.json

      - name: Post-Release / Send Error Notification
        if: ${{ failure() }}
        run: |
          curl -s \
          --form-string "user=${{ secrets.PUSHOVER_USER }}" \
          --form-string "token=${{ secrets.PUSHOVER_TOKEN }}" \
          --form-string "message=❗️ CI failed for $GIT_REPO/$GIT_BRANCH on commit $${{ github.sha }}." \
          --from-string "url=$RUN_URL" \
          --from-string "url_title=View Workflow Run" \
          https://api.pushover.net/1/messages.json
